- hosts: localhost
  name: main
  vars:
    source_discord_key: "./keys/discord/discord_backup_codes.txt"
    dest_discord_key: "{{ lookup('env', 'HOME') }}/keys/discord/discord_backup_codes.txt"
    source_key: "./keys/ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    brew_casks:
      - google-chrome
      - gimp
      - discord
      - bitwarden
      - docker
      - firefox
      - amethyst
      - brave-browser
    brew_packages:
      - git
      - coreutils
      - gnu-getopt
      - gnu-indent
      - gnu-sed
      - gnu-tar
      - gnu-typist
      - gnupg
      - gnutls
      - gawk
      - ffmpeg
      - pyenv
      - go
      - rustup-init
      - n
      - bat
      - cmake
      - elixir
      - exa
      - neovim
      - terraform
      - tmux
      - deno
      - grep
      - imagemagick
      - ripgrep
      - pure
      - protobuf
      - wget
      - lua
      - cmake
      - tree-sitter
      - stow
  tasks: 
  - include_tasks: "tasks/installhomebrew.yaml" 
  - include_tasks : tasks/installprograms.yaml
  - include_tasks: tasks/installcasks.yaml
  - include_tasks: tasks/dotfiles.yaml
  - include_tasks: tasks/zsh.yaml
  - include_tasks: tasks/node.yaml
  - include_tasks: tasks/neovim.yaml
  - include_tasks: tasks/discord.yaml
