- name: set up fish
  shell: echo $(which fish) | sudo tee -a /etc/shells
  become: yes
- name: set up default shell
  shell: chsh -s $(which fish)
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
- name: install oh-my-fish
  shell: curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish

