- name: Prereqs for Homebrew
  file:
    path: /usr/local/*
    state: directory
    mode: 0775
    owner: root
    group: wheel
    recurse: yes
  become: yes
- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args: 
    executable: /bin/bash
- name: allow multiple users
  file: 
    path: '{{ item }}'
    mode: '0775'
    owner: '{{ username }}'
    group: wheel
    recurse: yes
    state: directory
    become: yes
  ignore_errors: yes

- name: fix issues for multiple users
  become: yes
    # this line is long
  command: 'chmod -R +a "group:admin allow list,add_file,search,delete,add_subdirectory,delete_child,readattr,writeattr,readextattr,writeextattr,readsecurity,file_inherit,directory_inherit" {{ item }}'
  args: no 
  ignore_errors: yes

- name: Reset repo
  git: 
    repo=https://github.com/Homebrew/brew.git
    dest=/usr/local/Homebrew/Library
    clone=no
    update=yes
    force=yes

- name: Update brew ( first try )
  homebrew: 
    update_homebrew: true
  become: no 
  ignore_errors: yes
- name: Update brew ( second try )
  homebrew: update_homebrew=yes
  become: no



