- name: Ensure .ssh directory exists.
  become_user: root
  ansible.builtin.file:
    dest: "{{ dest_key | dirname }}"
    mode: '0700'
    state: directory
  tags:
    - dotfiles
    - ssh
- name: Install ssh key
  become_user: root
  ansible.builtin.copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - ssh
- name: Set authorized key took from file
  ansible.posix.authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  tags:
    - dotfiles
    - ssh
