- hosts : localhost
  name: install casks macos
  vars:
    brew_casks:
      - google-chrome
      - gimp
      - discord
      - btt
      - bitwarden
      - docker
      - firefox
      - amethyst
      - brave-browser
  tasks: 
  - name: install casks
    homebrew_cask:
      name: "{{ brew_casks }}"
      state: present
